[project]
name = "graphene-file-upload"
version = "0.1.0"
description = "Add a short description here"
authors = ["Alex Kerney <abk@mac.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
test = "py.test -v tests/"

[dependencies]
tox = ">=4.14.1,<4.15"
python = "~=3.10"
pytest = ">=8.1.1,<8.2"
pytest-django = ">=4.8.0,<4.9"
django = ">=5.0.3,<5.1"
pip = ">=24.0,<25"
